### ISSUE TITLE
did it die

### ISSUE THREAD

**Issue by Flaque** [devinroche/scheduleBuilder#15]
is it ded devin

**Comment by devinroche** [comment]
i tried to rebuild it but i wasnt making enough progress. this one has some bugs but we could still update the classes and make it live?

**Comment by Flaque** [comment]
I could help

**Comment by Flaque** [comment]
why is there bower? Also what things need to be done? Do you remember what the bugs were?

**Comment by tdurnford** [comment]
I just need to update the course catalog on the backend and tweak a couple of things. Not sure what you need to do on the front end. We also need to figure out the best way to deploy the app - maybe Evan knows better than us how to do that properly. 

If we want to keep working on this, let me know.

**Comment by devinroche** [comment]
@Flaque not sure i just used a yeoman angular skeleton to get off the ground faster.. the only problem (that I remember) on the frontend was when you click a course from the calendar of generated schedules the application crashes and you have to close the tab...

**Comment by Flaque** [comment]
Hey @tdurnford did you actually do that? That seems like spam/worm-virus.

**Comment by tdurnford** [comment]
Was me. Meant to share that somewhere else.

**Comment by tdurnford** [comment]
Hi there,

In case you missed it, TJ Durnford (tjdford@gmail.com) shared "Cannabis Digital Marketing" with you on Dropbox.

View on Dropbox[1]

Thanks!
- The Dropbox Team

____________________________________________________
 Dropbox, Inc. 
 PO Box 77767, San Francisco, CA 94107 
View Privacy Policy[2] | Unsubscribe[3]

[1]: https://www.dropbox.com/l/scl/AABT1WN7OJoY7UuPQ5XzaMBe8f5jO9i7gmk
[2]: https://www.dropbox.com/l/AADH6OgcvRzdjSL9T2pPHkw4H-9rGuAvexo/privacy
[3]: https://www.dropbox.com/l/AABZritDOW6eM-ZEeMZj0OZ0ZGdKi2LzCMg
